# Generated by Django 4.2.7 on 2026-01-31 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Original filename of uploaded CSV", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded CSV file", upload_to="datasets/%Y/%m/%d/"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when dataset was uploaded",
                    ),
                ),
                (
                    "data_json",
                    models.JSONField(help_text="Complete dataset in JSON format"),
                ),
                (
                    "total_equipment",
                    models.IntegerField(
                        default=0, help_text="Total number of equipment records"
                    ),
                ),
                (
                    "avg_flowrate",
                    models.FloatField(
                        blank=True,
                        help_text="Average flowrate across all equipment",
                        null=True,
                    ),
                ),
                (
                    "avg_pressure",
                    models.FloatField(
                        blank=True,
                        help_text="Average pressure across all equipment",
                        null=True,
                    ),
                ),
                (
                    "avg_temperature",
                    models.FloatField(
                        blank=True,
                        help_text="Average temperature across all equipment",
                        null=True,
                    ),
                ),
                (
                    "equipment_distribution",
                    models.JSONField(
                        default=dict, help_text="Count of each equipment type"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded this dataset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-uploaded_at"],
                        name="api_dataset_user_id_82ccec_idx",
                    )
                ],
            },
        ),
    ]
